  
version: '3'
services:
  nginx:
    container_name: nginx
    image: docker.io/licass/casasnginx
    ports:
      - '80:80'

  php:
    container_name: php
    image: docker.io/licass/casasphp
    ports:
      - '9000:9000'

  mysql:
    container_name: mysql
    image: docker.io/licass/casasdb
    ports:
      - '3306:3306'

  
   

